### ISSUE TITLE
Opencart 2.1.0.2

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#11]
It dont seem to work with Opencart 2.1.0.2.

**Comment by asbjornu** [comment]
@Freakshows Thanks for letting us know. What is it that doesn't work? Do you get an error message you can share with us?

**Comment by Freakshows** [comment]
Hi
I dont get any events in error log, and it is enabled, but when i am going to modules/payments/PayEx Payments - to edit the module its going to a blank page with a line at the top saying:
**Fatal error: Call to undefined method Loader::library() in /xxxxx/xxxxxx/admin/controller/payment/payex.php on line 84**

**Comment by aait** [comment]
I think this is fixed now, see https://github.com/PayEx/PayEx.OpenCart2/commit/5f71b51ff5033fd72f8d980a02c63dedddecb9ed
