### ISSUE TITLE
Options in module request.

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#13]
Would it be possible to have some sort of version numbering in releases?
Aslo:
Option in module for forcing language on payex landing page
Option in module to show the "new" responsive payex landing page (see attachemt)
Option in module: seperate page for the test account data.

![capture](https://cloud.githubusercontent.com/assets/13005141/13423164/a46d61f4-df99-11e5-903f-9f0c89d6b2df.PNG)

**Comment by Freakshows** [comment]
Is there any way to check what build/version is installed and in use on a site, any files that can identify version in use?
Also, it would be great with norwegian translation ("norsk") folder in releases.

**Comment by aait** [comment]
1) Client lanugage option was implemented in v1.1.2
2) Responsive design was implemented
3) Unnecessary option
