### ISSUE TITLE
Order goes canceled when refund

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#18]
I am using PayEx version 1.05 and it seems that orders goes to canceled status when i do a refund? i get that i may do so if i do a complete refund, but not when i do a partial refund.
OC 2.1.0.2

**Comment by aait** [comment]
Please attach screenshot of payex configuration from admin backend

**Comment by Freakshows** [comment]
![capture](https://cloud.githubusercontent.com/assets/13005141/20429832/4c0f56a4-ad91-11e6-9d12-ac89eeaa13ee.PNG)

**Comment by aait** [comment]
Unable to reproduce problem. I'm tried to refund order in opencart admin backend. And refund was success.
