### ISSUE TITLE
PayEx Tab in order page

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#19]
It would be really helpful to have a PayEx tab in the order page like the PayPal module have (see picture) with transaction details and **view** / **refund** option for further operation and handling of the order.

The PayPal tab is only visible when the order is paid using PayPal.

![capture](https://cloud.githubusercontent.com/assets/13005141/20425446/d5cfdac4-ad7a-11e6-9972-8ef951af3d47.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13005141/20425451/ddf79bba-ad7a-11e6-9987-54b949719714.PNG)

**Comment by aait** [comment]
It would require a core patch and works for PayPal because PayPal is integrated in OpenCart core

**Comment by asbjornu** [comment]
@Freakshows: Thanks for the feature suggestion. It would be really nice if you could suggest to WooCommerce to make an API for this, so we can offer this functionality in our module as well.

**Comment by Freakshows** [comment]
@asbjornu I would do that if I used WooCommerce :) i am on OpenCart 2.1.0.2 :)
But it couldnt be that hard to get OC support for this module, i mean they are great guys to talk to and opencart dev is here on github, look for "Daniel" (oc boss)

**Comment by asbjornu** [comment]
@Freakshows Sorry, I was just going through the issues and mixed which repository I was looking at. I of course meant OpenCart. 😄  But yea, my request remains: request OpenCart to implement an API for this, so other payment providers can add their tab to the view as well. It is obviously a great feature to have regardless of which payment provider you're using. 👍
