### ISSUE TITLE
Getting error message in PayEx admin

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#2]
I am getting a few error messages in PayEx Merchant Admin saying:
Code - Order_AmountNotEqualOrderLinesTotal
Description - Amount on initialized order is not equal to total on orderLines
I am not using any rounding features and do not ever get this kinda error with paypal.

I am loosing buissness if this continues and need a solution
Opencart event does not register anything about this issue.

opencart version 2.0.3.1

Also, version numbering / specification of this module would be great.

Thanks

**Comment by aait** [comment]
Hi,

Do you use any kind of discounts? Can you give me access to your shop so I can investigate? Please email to info@aait.se Also include one example order that shows this behaviour.

**Comment by Freakshows** [comment]
Thanks, i have sent you an email with details

**Comment by aait** [comment]
Thanks. Still await for  information how to reproduce this problem. Thanks for your cooperation.
