### ISSUE TITLE
Norwegian language. for the payex window

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#25]
How can I force Norwegian language. for the payex window after the new option to set language in module version v1.1.2 was added? For some reason I cant change it to other that "Detect Automatically".

Anyway, I have gone back to using module version 1.1.1 sins this module don't give the errors that v1.1.2 gives, but I would still like to force a Norwegian payex window. I have done this on earlier module versions, but I cant seem to find the howto i got from payex support some time ago.

Using OC 2302

**Comment by Freakshows** [comment]
Anyone home? :)

**Comment by aait** [comment]
Hello, to hardcode Norwegian you can do follow:
Open /catalog/controller/payment/payex.php
Find line:
`'clientLanguage' => $this->getLocale($this->language->get('code'))`
Replace to:
`'clientLanguage' => 'nb-NO'`
