### ISSUE TITLE
Wrong total in the payex window

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#29]
Version 112 and 113 (the two tested) show wrong total in the PayEx Window when using a voucher code, while the PayPal payment show correct total and have no issues. (see attachments)
I have tested with a range of products, the totals between cart and payex window always differs, when voucher is applied. Works fine when voucher code is NOT used. The other payment gateways i use have no issues with or without voucher applied.

![cart](https://user-images.githubusercontent.com/13005141/27012243-a0230baa-4ecc-11e7-8c4e-dcdfbcfb622c.PNG)
![paypal](https://user-images.githubusercontent.com/13005141/27012245-a6714b34-4ecc-11e7-9dfe-9cf57948b6e3.PNG)
![payex](https://user-images.githubusercontent.com/13005141/27012249-a9b260d0-4ecc-11e7-94e2-1bd9efe69dc8.PNG)

**Comment by olegisk** [comment]
@Freakshows Regarding Vouchers. It's standard feature of OpenCart (coupon discount) or 3party module?

**Comment by Freakshows** [comment]
There is no 3party module installed handling vouchers, this is std opencart
