### ISSUE TITLE
SSL operation failed with code 1

### ISSUE THREAD

**Issue by diztie** [PayEx/PayEx.OpenCart2#3]
i get this when i press confirm order
Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php on line 220Warning: SoapClient::SoapClient(): Failed to enable crypto in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php on line 220Warning: SoapClient::SoapClient(https://external.payex.com/pxorder/pxorder.asmx?WSDL): failed to open stream: operation failed in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php on line 220Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity "https://external.payex.com/pxorder/pxorder.asmx?WSDL" in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php on line 220 Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://external.payex.com/pxorder/pxorder.asmx?WSDL' : failed to load external entity "https://external.payex.com/pxorder/pxorder.asmx?WSDL" in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php:220 Stack trace: #0 /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php(220): SoapClient->SoapClient('https://externa...', Array) #1 /storage/content/84/173884/jaktverket.se/public_html/catalog/controller/payment/payex.php(89): Px->__call('Initialize8', Array) #2 /storage/content/84/173884/jaktverket.se/public_html/catalog/controller/payment/payex.php(89): Px->Initialize8(Array) #3 [internal function]: ControllerPaymentPayex->confirm(Array) #4 /storage/content/84/173884/jaktverket.se/public_html/vqmod/vqcache/vq2-system_modification_system_engine_action.php(65): call_user_func(Array, Array) #5 /storage/content/84/173884/jaktverket.se/public_html/vqmod/vqcache/vq2-system_modification in /storage/content/84/173884/jaktverket.se/public_html/system/library/Px/Px.php on line 220

**Comment by aait** [comment]
It seems problem can be related to the openSSL configuration on your server.
Similar issues for example https://github.com/composer/composer/issues/3346
Please contact with you hosting administrator to solve this problem.
Also you can do  a workaround:
Open /catalog/controller/payment/payex.php

Find:
self::$_px = new Px();

Replace to:
self::$_px = new Px(array('ssl_verify' => false));
