### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#32]
Not an issue, but is there any changes in the language files from release 1.1.3 to 1.1.4? Reason for asking is that i already got a norwegian translation done, hate to do it again :)

Also, is there an opecart 3 version in the roadmap?

Looking forward to test 1.1.4 :)

**Comment by olegisk** [comment]
Hi @Freakshows 
I will let you know about opencart v3.
Can you provide files with norwegian translation? I will include your translation in next release

**Comment by Freakshows** [comment]
I have only the files i need translated, but can i use the files from 113 in 114?

**Comment by olegisk** [comment]
Yes. You can use language files from 113

**Comment by Freakshows** [comment]
If it delete the old "vendor" folder, i do not get into the payex payments module page (only the big white browser window". I put it back and all ok?

Error log:
`2017-10-14 16:20:26 - PHP Warning:  require_once(/home/3/d/doobie/www/vendor/payex/php-api/src/PayEx/Px.php): failed to open stream: No such file or directory in /home/3/d/doobie/www/admin/controller/extension/payment/payex.php on line 6
2017-10-14 16:20:36 - PHP Warning:  require_once(/home/3/d/doobie/www/system/../vendor/payex/php-api/src/PayEx/Px.php): failed to open stream: No such file or directory in /home/3/d/doobie/www/admin/controller/extension/payment/payex.php on line 6
2017-10-14 16:20:38 - PHP Warning:  require_once(/home/3/d/doobie/www/system/../vendor/payex/php-api/src/PayEx/Px.php): failed to open stream: No such file or directory in /home/3/d/doobie/www/admin/controller/extension/payment/payex.php on line 6`

**Comment by olegisk** [comment]
Hi @Freakshows 
Our payment module don't have "admin/controller/extension/payment/payex.php"

**Comment by Freakshows** [comment]
thats not much of an awnser, look at this line:
2017-10-14 16:20:26 - PHP Warning: require_once(/home/3/d/doobie/www/vendor/payex/php-api/src

**Comment by olegisk** [comment]
Yes, i saw it. But our module have file "admin/controller/extension/payment/payex.php".
If you have custom changes/files that you should fix path manually.

**Comment by Freakshows** [comment]
Ok, i have gone thru the module and unstalled it manualy (gone thru directory by directory and deleted files) just to see if there is some old crap from erlier versions left in there, and almost all payex related stuff did go away, BUT i have this entry left in my module page??
![skjermbilde1](https://user-images.githubusercontent.com/13005141/31583084-3f2bcc1c-b194-11e7-8e7f-3d6ad5a5ce00.PNG)

I have no idea on what could possably be left of files,,,hmmm

**Comment by olegisk** [comment]
Check directory /admin/controller/payment
I think there are files from https://github.com/PayEx/PayEx.OpenCart2/tree/master/admin/controller/payment

**Comment by Freakshows** [comment]
After a ssh search i found it here for some reason...hmm
admin/controller/extension/payment/payex.php

**Comment by olegisk** [comment]
Which OpenCart version you have?

**Comment by Freakshows** [comment]
Version 2.3.0.2

**Comment by olegisk** [comment]
It's ok. But it's very strange that you are have payex files in admin/controller/extension/payment/

**Comment by Freakshows** [comment]
O'boy, getting rid of that one file in admin/controller/extension/payment/payex.php solved a lot of issues for me; no errors in log just by entring the module settings, and i no longer have to hard code this to get norwegian payex page 
NO MORE:
File: catalog/controller/payment/payex.php
Find line:
'clientLanguage' => $language
Replace with:
'clientLanguage' => 'nb-NO'

And have only the original "vendors" dir also works :)

This makes me a happy camper :)
Now i have just 2 more sites to clean up :/

**Comment by Freakshows** [comment]
This can be closed :)
