### ISSUE TITLE
Issue with new version

### ISSUE THREAD

**Issue by Freakshows** [PayEx/PayEx.OpenCart2#34]
I am having an issue with a module i am using to transfer order amount to my accounting program (Fiken.no), it seems the that it for some reason do not pick up PayEx as an alternativ payment option and there for i am not able to link payment option used by the custormer and the account number it is paid to (see screenshot)
![skjermbilde](https://user-images.githubusercontent.com/13005141/31604222-f3b9c5ac-b262-11e7-8e33-12d269a2eb82.PNG)

**Comment by olegisk** [comment]
Attached module get payment methods from controller/extension/payment directory. But our module use old-style directory controller/payment. So invisible for fiken module. You can contact with developers of fiken module to fix it.

**Comment by Freakshows** [comment]
Thank you for the reply.
Normal thing to do would probably be get the PayEx module for OC 2.3.0.2 to use the updated path's, one would think, not to get new modules like "Fiken" to use out-dated path's. Just saying :)
But Fiken developer provided a quick fix for me, that is good karma. :)
