### ISSUE TITLE
factoring fee

### ISSUE THREAD

**Issue by diztie** [PayEx/PayEx.OpenCart2#5]
factoring fee module don't work with "PayEx Payments"

**Comment by aait** [comment]
Hi,
It is correct that no invoice fee is implemented for the PayEx Payment redirect  module. The Payex Payment module use Ledger service http://www.payexpim.com/payment-methods/invoice/. For normal business to consumer invoicing PayEx recommends FInancing Invoice/ Factoring which is a direct  method. There the invoice fee works, see attached picture 
![oc_factoring](https://cloud.githubusercontent.com/assets/6286270/10907036/f8e695a0-8226-11e5-9532-54d401a1e1f2.png)
