### ISSUE TITLE
Cant save settings in Opencart

### ISSUE THREAD

**Issue by forslund86** [PayEx/PayEx.OpenCart2#6]
Hi, i do have some problem regarding your modules for Opencart 2.
Installation went smooth, but when im trying to activate the modules they wont save their changes and next time i enter they have the start settings again.

Also i wonder this modules compability to other modules for shipping and templates such as Journal 2.

**Comment by aait** [comment]
Hi,
Using the latest from this repository?
Compatibility with Journal 2 has not been tested.

**Comment by forslund86** [comment]
Hi, yes i downloaded the latest from your github, do you need to have a
legit merchant ID and encryption key to being able to save or can you just
enter anything?

Ive tried it aswell with default theme and cant still save the settings ive
enterd.

**Comment by aait** [comment]
Please send your access details to info@aait.se and we will look at it

**Comment by aait** [comment]
Solved by instructions.
